apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore 
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: daprsecrects-kv
  - name: azureTenantId
    value: "9a806aac-c25f-4c69-8f27-9feb78446b4b"
  - name: azureClientId
    value: "d4e2ab14-5aaa-4112-b3cd-17012d1c5d5f"
  - name: azureClientSecret
    value : "lR68Q~IGf3z87aqNO5uozknVPMDO87Xjo.1NtakS"
